project:
  type: website

website:
  title: "IS415 Project - AY2024/2025 Term 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project_proposal.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



