project:
  type: website

website:
  favicon: "/images/logo.png"
  navbar:
    logo: "/images/logo.png"
    title: "JB: The New Frontier?" 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: project_proposal.qmd
      - text: Proposal

format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: rgb(0, 153, 255)
    toc: true



