project:
  type: website

website:
  title: "JB: The New Frontier?"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: project_proposal.qmd
      - text: Proposal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



