project:
  type: website

website:
  favicon: "/images/logo.png"
  navbar:
    logo: "/images/logo.png"
    title: "JB: The New Frontier?" 
    left:
      - href: index.html
        text: Home
      - href: userguide.html
        text: User Guide
      - href: "https://chihao.shinyapps.io/is415-grp4-jb/"
        text: Shiny App
      - href: poster.html
        text: Poster
    right:
      - href: about.html
        text: About us

format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: rgb(0, 153, 255)
    toc: true



