---
title: "JB: The New Frontier?"
subtitle: "Geospatial Analytics Project Proposal - AY2024/2025 Term 1"
author: "Heng Kuan Xin, Kendrick Teo, Seah Chi Hao"
date: "2024-10-09"
date-modified: "last-modified"

execute: 
  eval: true
  echo: true
  freeze: true
---

## PP1. Motivation

Of late, housing prices in Singapore have been flying through the roof. Because of this, many Singaporeans who yearn for a private space of their own without breaking the bank have been snapping up properties in neighbouring [Johor Bahru, Malaysia](https://en.wikipedia.org/wiki/Johor_Bahru). How high will this drive property prices in the city, perhaps best known among Singaporeans as a cheap and easily accessible weekend shopping getaway? Compared to Singapore, what factors influence the JB property market? Where is each type of housing, catered to different income levels, clustered? And does it matter that JB's suburbs lack reliable access to public transport? This project aims to find the answers to these lingering questions and more, through a geospatial analysis on the property market of Johor Bahru and its emerging next-door neighbour, [Iskandar Puteri](https://en.wikipedia.org/wiki/Iskandar_Puteri)

## PP2. Issues the project will address

The project will make it easy for interested researchers and casual observers, especially those from Singapore, to understand the factors influencing the property market in Johor Bahru and Iskandar Puteri.

## PP3. Approach team plans to take to solve the problem

The proposed outline of the project will be as follows:

1. Vanilla and Emerging Hot/cold spot analysis on average/median property values for each *Mukim* in Johor Bahru and Iskandar Puteri (Pulai)
2. KDE on selected amenity types (e.g. schools, shopping malls, major transport nodes, commercial districts, industrial districts) in Johor Bahru using data scraped from OpenStreetMap
3. Building a hedonic pricing model for residential properties in Johor Bahru

## PP4. Relevant related work

We take inspiration from an earlier example done by senior Megan Sim (2021), who created a similar hedonic pricing model for the public housing market in Singapore in 2021.

## PP5. Early prototypes or storyboards

```{r}
pacman::p_load(sf, tmap, tidyverse)
malaysia_adm2 <- st_read(dsn = "data/geospatial/myadm2", layer = "geoBoundaries-MYS-ADM2") %>% st_transform(4326)
malaysia_adm3 <- st_read(dsn = "data/geospatial/myadm3", layer = "geoBoundaries-MYS-ADM3") %>% st_transform(4326)
tmap_mode('view')
tmap_options(check.and.fix = TRUE)
tm_shape(malaysia_adm2) + tm_polygons()
tm_shape(malaysia_adm3) + tm_polygons()
tmap_mode('plot')
```

## References

Sim, M. (2021, October 2025). Take-Home Exercise 3: Hedonic Pricing Models for Resale Prices of Public Housing in Singapore. [https://is415-msty.netlify.app/posts/2021-10-25-take-home-exercise-3/](https://is415-msty.netlify.app/posts/2021-10-25-take-home-exercise-3/)